# Generated by Django 4.2.2 on 2023-06-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=80)),
                ('cpf', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=200)),
                ('valor_emprestimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Aprovada', 'Aprovada'), ('Negada', 'Negada')], default='Aguardando', max_length=10)),
            ],
        ),
    ]
