# Generated by Django 4.2.2 on 2023-06-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='cpf',
            field=models.CharField(error_messages={'unique': 'Já existe uma proposta com este CPF.'}, max_length=11, unique=True),
        ),
    ]
